openapi: 3.0.3
info:
  title: Inditex Pricing API
  version: 1.0.0
  description: |
    REST API to query the applicable price of a product for a given brand at a specific date and time.
    Business rule: if multiple prices are valid, the one with the highest priority applies.
servers:
  - url: /api/v1
tags:
  - name: Prices
    description: Operations related to product prices

paths:
  /prices:
    get:
      tags: [Prices]
      summary: Get the applicable price
      operationId: getApplicablePrice
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: string
            example: "35455"
        - name: brandId
          in: query
          required: true
          schema:
            type: string
            example: "1"
        - name: applicationDate
          in: query
          required: true
          description: Date and time (ISO-8601) for which the price must be applied
          schema:
            type: string
            format: date-time
            example: "2020-06-14T16:00:00Z"
      responses:
        '200':
          description: Applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: No applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    Money:
      type: object
      required: [amount, currency]
      properties:
        amount:
          type: number
          format: double
          example: 35.50
        currency:
          type: string
          example: "EUR"
    PriceResponse:
      type: object
      required: [productId, brandId, priceList, startDate, endDate, priority, price]
      properties:
        productId:
          type: string
          example: "35455"
        brandId:
          type: string
          example: "1"
        priceList:
          type: string
          description: Identifier of the price list applied
          example: "2"
        startDate:
          type: string
          format: date-time
          example: "2020-06-14T15:00:00Z"
        endDate:
          type: string
          format: date-time
          example: "2020-06-14T18:30:00Z"
        priority:
          type: integer
          format: int32
          example: 1
        price:
          $ref: '#/components/schemas/Money'
    ApiError:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: "PRICE_NOT_FOUND"
        message:
          type: string
          example: "No applicable price found for given parameters"
        details:
          type: array
          items:
            type: string
