DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID VARCHAR(10) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    PRICE_LIST VARCHAR(10) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL
);